### ISSUE TITLE
Typo ?

### ISSUE THREAD

**Issue by vitormalencar** [cjpatoilo/rasper#1]
hey, buddy just an NP 💅  but I would like to ask you if this `hasEgual ` is intentional

https://github.com/cjpatoilo/rasper/blob/master/index.js#L18

**Comment by cjpatoilo** [comment]
Hmm I'm not sure. Do you have any idea how to improve this method name? In fact this code need to improve.

**Comment by alisonmonteiro** [comment]
`Egual` -> `Equal`? 🤔

**Comment by cjpatoilo** [comment]
Good call @vitormalencar 🚀 
Thank you so much
