### ISSUE TITLE
Arguments containing dashes are not parsed correctly

### ISSUE THREAD

**Issue by luciorubeens** [cjpatoilo/rasper#2]
I've tried using the [initify package](https://github.com/cjpatoilo/initify), however, if I choose a license with a 'dash' the value is not recognized.

### Steps to reproduce
`initify my-app --license apache-2.0` 

### Expected behavior
```js
{
  _: ['my-app'],
  license: 'apache-2.0'
}
```

### Actual behavior
```js
{
  _: ['my-app'],
  license: 'apache2.0'
}
```

So the license file is not found.

**Comment by cjpatoilo** [comment]
#3
